# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-13 03:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0002_contestant_percentage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='ip_ad',
            field=models.GenericIPAddressField(),
        ),
    ]
