# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-13 03:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0003_auto_20170413_0340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='category',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='vote',
            name='contestant',
            field=models.IntegerField(default=0),
        ),
    ]
