# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-13 04:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0004_auto_20170413_0341'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('category', models.IntegerField(default=0)),
                ('sum', models.IntegerField(default=0)),
            ],
        ),
    ]
