# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-13 04:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0005_sum'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contestant',
            name='category',
            field=models.IntegerField(default=0),
        ),
    ]
